### PR TITLE
Support latest node/nodewebkit

### PR DESCRIPTION
**Pull request by dhleong**
Builds on @porsager's work and uses the latest nan library compatibility

### CODE REVIEW

**Comment by amullins83** [comment]
How do we fix the merge conflicts so that this can be merged in?

**Comment by dhleong** [comment]
I haven't used this in quite some time, but I rebased off master and fixed the conflicts. Please let me know if there are any problems

**Comment by amullins83** [comment]
No problems. I tested with my devices on v0.10.35 and v0.11.13 on Windows and Linux and it all works beautifully. I hope this gets merged to master.

**Comment by jbsulli** [comment]
Sadly, I'm getting a lot of errors in OSX 10.9.5 Mavericks. It might just be that I don't know what I'm doing though...

```
> node-hid@0.3.2 install /Users/xserve/josh/node_modules/node-hid
> sh install.sh

  CC(target) Release/obj.target/hidapi/hidapi/mac/hid.o
../hidapi/mac/hid.c:255:20: warning: comparison of integers of different signs: 'CFIndex' (aka 'long') and 'size_t'
      (aka 'unsigned long') [-Wsign-compare]
                if (chars_copied == len)
                    ~~~~~~~~~~~~ ^  ~~~
../hidapi/mac/hid.c:295:20: warning: comparison of integers of different signs: 'CFIndex' (aka 'long') and 'size_t'
      (aka 'unsigned long') [-Wsign-compare]
                if (used_buf_len == len)
                    ~~~~~~~~~~~~ ^  ~~~
2 warnings generated.
  LIBTOOL-STATIC Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc:51:79: error: no member named 'New' in 'v8::String'
  virtual Handle<Value> asV8Exception() const { return ThrowException(String::New(message().c_str())); }
                                                                      ~~~~~~~~^
../src/HID.cc:195:32: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
    argv[0] = Exception::Error(String::New(iocb->_error->message().c_str()));
                               ^~~~~~~~~~~
                               New
../src/HID.cc:77:21: note: 'New' declared here
  static NAN_METHOD(New);
                    ^
../../nan/nan.h:1256:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/HID.cc:195:44: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an rvalue of type
      'const char *'
    argv[0] = Exception::Error(String::New(iocb->_error->message().c_str()));
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/HID.cc:77:10: note: passing argument to parameter 'args' here
  static NAN_METHOD(New);
         ^
../../nan/nan.h:1256:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../../nan/nan.h:162:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
../src/HID.cc:200:16: error: no member named 'GetCurrent' in 'v8::Context'
      Context::GetCurrent()->Global()->Get(String::New("Buffer") )
      ~~~~~~~~~^
../src/HID.cc:200:44: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
      Context::GetCurrent()->Global()->Get(String::New("Buffer") )
                                           ^~~~~~~~~~~
                                           New
../src/HID.cc:77:21: note: 'New' declared here
  static NAN_METHOD(New);
                    ^
../../nan/nan.h:1256:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/HID.cc:200:56: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an lvalue of type
      'const char [7]'
      Context::GetCurrent()->Global()->Get(String::New("Buffer") )
                                                       ^~~~~~~~
../src/HID.cc:77:10: note: passing argument to parameter 'args' here
  static NAN_METHOD(New);
         ^
../../nan/nan.h:1256:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../../nan/nan.h:162:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
../src/HID.cc:203:68: error: too few arguments to function call, expected 2, have 1
    Handle<Value> nodeBufferArgs[1] = { Integer::New(message.size()) };
                                        ~~~~~~~~~~~~               ^
/Users/xserve/.node-gyp/0.11.13/deps/v8/include/v8.h:2074:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../src/HID.cc:221:13: error: use of undeclared identifier 'NanNewLocal'
  argv[0] = NanNewLocal<Value>(Undefined());
            ^
../src/HID.cc:221:25: error: 'Value' does not refer to a value
  argv[0] = NanNewLocal<Value>(Undefined());
                        ^
/Users/xserve/.node-gyp/0.11.13/deps/v8/include/v8.h:1407:17: note: declared here
class V8_EXPORT Value : public Data {
                ^
../src/HID.cc:221:32: error: no matching function for call to 'Undefined'
  argv[0] = NanNewLocal<Value>(Undefined());
                               ^~~~~~~~~
/Users/xserve/.node-gyp/0.11.13/deps/v8/include/v8.h:336:28: note: candidate function not viable: requires single argument 'isolate',
      but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/HID.cc:222:13: error: use of undeclared identifier 'NanNewLocal'
  argv[1] = NanNewLocal<Value>(Undefined());
            ^
../src/HID.cc:222:25: error: 'Value' does not refer to a value
  argv[1] = NanNewLocal<Value>(Undefined());
                        ^
/Users/xserve/.node-gyp/0.11.13/deps/v8/include/v8.h:1407:17: note: declared here
class V8_EXPORT Value : public Data {
                ^
../src/HID.cc:222:32: error: no matching function for call to 'Undefined'
  argv[1] = NanNewLocal<Value>(Undefined());
                               ^~~~~~~~~
/Users/xserve/.node-gyp/0.11.13/deps/v8/include/v8.h:336:28: note: candidate function not viable: requires single argument 'isolate',
      but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/HID.cc:245:35: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
    NanReturnValue(ThrowException(String::New("need one callback function argument in read")));
                                  ^~~~~~~~~~~
                                  New
../../nan/nan.h:231:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../src/HID.cc:77:21: note: 'New' declared here
  static NAN_METHOD(New);
                    ^
../../nan/nan.h:1256:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/HID.cc:245:47: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an lvalue of type
      'const char [44]'
    NanReturnValue(ThrowException(String::New("need one callback function argument in read")));
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:231:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../src/HID.cc:77:10: note: passing argument to parameter 'args' here
  static NAN_METHOD(New);
         ^
../../nan/nan.h:1256:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../../nan/nan.h:162:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
../src/HID.cc:264:35: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
    NanReturnValue(ThrowException(String::New("need report ID and non-zero length parameter in getFeatureReport")));
                                  ^~~~~~~~~~~
                                  New
../../nan/nan.h:231:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../src/HID.cc:77:21: note: 'New' declared here
  static NAN_METHOD(New);
                    ^
../../nan/nan.h:1256:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/HID.cc:264:47: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an lvalue of type
      'const char [65]'
    NanReturnValue(ThrowException(String::New("need report ID and non-zero length parameter in getFeatureReport")));
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:231:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../src/HID.cc:77:10: note: passing argument to parameter 'args' here
  static NAN_METHOD(New);
         ^
../../nan/nan.h:1256:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../../nan/nan.h:162:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
../src/HID.cc:278:35: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
    NanReturnValue(ThrowException(String::New("could not get feature report from device")));
                                  ^~~~~~~~~~~
                                  New
../../nan/nan.h:231:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../src/HID.cc:77:21: note: 'New' declared here
  static NAN_METHOD(New);
                    ^
../../nan/nan.h:1256:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/HID.cc:278:47: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an lvalue of type
      'const char [41]'
    NanReturnValue(ThrowException(String::New("could not get feature report from device")));
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:231:65: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(value)
                                                                ^
../src/HID.cc:77:10: note: passing argument to parameter 'args' here
  static NAN_METHOD(New);
         ^
../../nan/nan.h:1256:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../../nan/nan.h:162:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/HID/src/HID.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "install"
gyp ERR! cwd /Users/xserve/josh/node_modules/node-hid
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! node-hid@0.3.2 install: `sh install.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.3.2 install script.
npm ERR! This is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sh install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "git://github.com/dhleong/node-hid.git"
npm ERR! cwd /Users/xserve/josh
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/xserve/josh/npm-debug.log
npm ERR! not ok code 0
```

**Comment by amullins83** [comment]
Thanks for the error report. It looks like the conversion to NAN was not quite complete after all. I wonder why it worked on my Windows system. Maybe because I had Node 0.10 installed first and just added 0.11 for testing? Anyway, this should be fixable.

**Comment by jbsulli** [comment]
Not entirely sure it is NAN. If you look at the first error, it almost seems like the program doesn't have the V8 string functions? I don't know much about C++ though and the build part of npm is still a mystery to me... do I could really be wrong. Would be awesome to get it working though! Want to get input from USB scales.

**Comment by dhleong** [comment]
Looks like I missed some new v8 methods after the rebase. Hmm....

**Comment by dhleong** [comment]
Added some more Nan, but nw-gyp is failing to build for any configuration other than 0.8.6

Thoughts? 

```
In file included from ../src/HID.cc:35:
../node_modules/nan/nan.h:1467:5: error: no matching function for call to 'uv_async_init'
    uv_async_init(
    ^~~~~~~~~~~~~
/Users/dhleong/.nw-gyp/0.11.5/src/../deps/uv/include/uv.h:1360:15: note: candidate function not
      viable: no known conversion from 'void (uv_async_t *)' to 'uv_async_cb' (aka
      'void (*)(uv_async_t *, int)') for 3rd argument
UV_EXTERN int uv_async_init(uv_loop_t*,
              ^
1 error generated.
make: *** [Release/obj.target/HID/src/HID.o] Error 1
```

**Comment by jbsulli** [comment]
Same as https://github.com/rvagg/nan/issues/151 maybe?

**Comment by dhleong** [comment]
Ah. Yeah, adding the explicit cast to `nan.h` fixes the compile error. Not sure why it's not actually included in the lib...?

**Comment by jbsulli** [comment]
Interesting. Haven't done C++ programming in forever... can't say I miss the casting, pointers, etc. :P

**Comment by amullins83** [comment]
It wouldn't be so bad except that Google decided to completely change V8. Rod did a great job wrapping the differences with NAN, but it's still quirky.

**Comment by dbrwn** [comment]
I believe #75 crept back in at 96334787f753a1716229ef386be7e506be514f27.

**Comment by dhleong** [comment]
@dbrwn Fixed

**Comment by rjsteinert** [comment]
Tested on Mac OS 10.9.5 and node v0.11.13, build works! Fails on node v0.12.0.

**Pull request merged**
